import type { AuthoredRaceCourse } from './courseAuthoring';

export const AUTHORED_RACE_COURSES: readonly AuthoredRaceCourse[] = [
  {
    id: 'claim-shakedown',
    name: 'Claim Shakedown',
    summary: 'A short league qualifier through the open field and back to the base beacon.',
    seed: 10100,
    startPosition: [0, 0, 180],
    medals: { gold: 46, silver: 58, bronze: 74 },
    design: {
      biome: 'open-claim-space',
      difficulty: 1,
      skillFocus: 'Basic gate reading, boost timing, and gentle recovery arcs.',
      rhythm: ['straight launch', 'wide high setup', 'easy lateral correction', 'clean return'],
      generationPattern: 'Sparse open-claim shell with wide gate bubbles and only mild gravity near the intended route.',
    },
    field: {
      gateClearance: 190,
      routeCorridor: 220,
      gravityAnchorCount: 0,
      hazardBias: 'low',
      asteroidTuning: {
        PROCEDURAL_COUNT: 520,
        SPHERE_OUTER: 4200,
        RADIUS_RANGE: 165,
        MASS_COEF: 9.5,
        CORE_DENSITY_RANGE: 1.2,
      },
    },
    gates: [
      { id: 'launch-slot', label: 'Launch Slot', position: [0, 40, -480], radius: 96, beat: 'Confirm forward launch and first gate read.' },
      { id: 'high-line', label: 'High Line', position: [360, 170, -980], radius: 92, normal: [-0.35, -0.1, 1], beat: 'Teach a high, soft correction without heavy gravity.' },
      { id: 'belter-turn', label: 'Belter Turn', position: [-240, -80, -1420], radius: 88, normal: [0.4, 0.1, 1], beat: 'Introduce lateral route planning.' },
      { id: 'base-return', label: 'Base Return', position: [0, 0, 110], radius: 108, beat: 'Finish on a forgiving home-line target.' },
    ],
  },
  {
    id: 'dead-iron-sweep',
    name: 'Dead Iron Sweep',
    summary: 'A mid-field race built around fast bends near heavier wells.',
    seed: 20420,
    startPosition: [0, 0, 180],
    medals: { gold: 82, silver: 104, bronze: 132 },
    design: {
      biome: 'dead-iron-belt',
      difficulty: 3,
      skillFocus: 'Committed slingshot bends and quick recovery after gravity-assisted turns.',
      rhythm: ['yard exit', 'hard sweep right', 'long falling line', 'cross-field drift', 'return burn', 'finish'],
      generationPattern: 'Medium-dense Dead Iron belt with stronger wells outside bend exits and moderate route-corridor pressure.',
    },
    field: {
      gateClearance: 170,
      routeCorridor: 175,
      gravityAnchorCount: 2,
      hazardBias: 'medium',
      asteroidTuning: {
        PROCEDURAL_COUNT: 820,
        SPHERE_OUTER: 6500,
        RADIUS_RANGE: 225,
        MASS_COEF: 12.5,
        CORE_DENSITY_RANGE: 1.7,
        SIZE_INNER_MAX: 0.52,
      },
    },
    gates: [
      { id: 'yard-exit', label: 'Yard Exit', position: [-180, 60, -680], radius: 96, beat: 'Move out of the launch lane into belt traffic.' },
      { id: 'iron-hook', label: 'Iron Hook', position: [760, -160, -1520], radius: 92, normal: [-0.5, 0.1, 1], beat: 'First real gravity-assisted hook.' },
      { id: 'long-fall', label: 'Long Fall', position: [260, 360, -2600], radius: 98, normal: [0.1, -0.3, 1], beat: 'Hold speed through a longer falling section.' },
      { id: 'cross-drift', label: 'Cross Drift', position: [-840, 120, -2360], radius: 96, normal: [0.7, -0.1, 1], beat: 'Cross the field without bleeding too much speed.' },
      { id: 'return-burn', label: 'Return Burn', position: [-420, -140, -780], radius: 92, normal: [0.45, 0.1, -1], beat: 'Recover from the cross-field drift and line up the finish.' },
      { id: 'league-line', label: 'League Line', position: [0, 0, 120], radius: 110, beat: 'Fast home-line finish.' },
    ],
  },
  {
    id: 'black-core-run',
    name: 'Black Core Run',
    summary: 'A deep-field sprint where close gravity passes are faster than clean lines.',
    seed: 31990,
    startPosition: [0, 0, 180],
    medals: { gold: 138, silver: 172, bronze: 218 },
    design: {
      biome: 'black-core-field',
      difficulty: 4,
      skillFocus: 'Reading large gravity wells without requiring a near-perfect capture line.',
      rhythm: ['deep launch', 'wide left setup', 'controlled sink', 'knife-edge pass', 'core-side return', 'snapback', 'home burn'],
      generationPattern: 'Large deep-field wells with wider gate bubbles than an expert course and fewer inner-shell hazards.',
    },
    field: {
      gateClearance: 210,
      routeCorridor: 210,
      gravityAnchorCount: 3,
      hazardBias: 'medium',
      asteroidTuning: {
        PROCEDURAL_COUNT: 860,
        SPHERE_OUTER: 7800,
        RADIUS_RANGE: 245,
        RADIAL_BIAS: 0.84,
        SIZE_INNER_MAX: 0.48,
        MASS_COEF: 13.2,
        CORE_DENSITY_MIN: 0.78,
        CORE_DENSITY_RANGE: 1.55,
        DRIFT_RANGE: 0.28,
      },
    },
    gates: [
      { id: 'deep-ticket', label: 'Deep Ticket', position: [120, -80, -760], radius: 104, beat: 'Leave the yard with more room than the old expert opening.' },
      { id: 'hard-left', label: 'Hard Left', position: [960, 220, -1680], radius: 104, normal: [-0.48, -0.12, 1], beat: 'A wide, readable setup for the first major bend.' },
      { id: 'sinkhole', label: 'Sinkhole', position: [560, -340, -3040], radius: 104, normal: [-0.18, 0.38, 1], beat: 'Use the well, but do not require a razor-thin drop.' },
      { id: 'knife-edge', label: 'Knife Edge', position: [-820, -90, -3500], radius: 100, normal: [0.62, 0.04, 1], beat: 'Keep the scary pass, with more margin and less depth.' },
      { id: 'dead-core', label: 'Dead Core', position: [-1120, 450, -2260], radius: 104, normal: [0.46, -0.25, -1], beat: 'Return around the core without forcing maximum gravity exposure.' },
      { id: 'snapback', label: 'Snapback', position: [-360, 150, -1060], radius: 104, normal: [0.28, -0.05, -1], beat: 'Let players recover before the final burn.' },
      { id: 'home-burn', label: 'Home Burn', position: [0, 0, 125], radius: 116, beat: 'Larger finish gate for high-speed arrivals.' },
    ],
  },
];
