import type { AuthoredRaceCourse } from './courseAuthoring';

const LEGACY_RACE_COURSES: readonly AuthoredRaceCourse[] = [
  {
    id: 'lab-thrust-brake',
    name: 'Lab: Thrust Brake',
    summary: 'Flight lab: straight lane for left-stick acceleration/braking, boost rhythm, and stopping distance.',
    seed: 40001,
    startPosition: [0, 0, 180],
    medals: { gold: 24, silver: 34, bronze: 48 },
    design: {
      biome: 'open-claim-space',
      difficulty: 1,
      skillFocus: 'Left-stick thrust, boost, brake damping, and speed readability.',
      rhythm: ['launch', 'boost lane', 'brake check', 'finish'],
      generationPattern: 'Empty straight lab lane with no gravity or procedural hazards.',
    },
    field: {
      gateClearance: 360,
      routeCorridor: 440,
      gravityAnchorCount: 0,
      hazardBias: 'low',
      asteroidTuning: { PROCEDURAL_COUNT: 0 },
    },
    gates: [
      { id: 'lab-burn-1', label: 'Burn 1', position: [0, 0, -440], radius: 170, beat: 'Push left stick up and feel the initial curve.' },
      { id: 'lab-burn-2', label: 'Burn 2', position: [0, 0, -1040], radius: 170, beat: 'Boost through the lane.' },
      { id: 'lab-brake', label: 'Brake Check', position: [0, 0, -1640], radius: 190, beat: 'Pull left stick down to slow without flipping the line.' },
      { id: 'lab-brake-finish', label: 'Finish', position: [0, 0, -2260], radius: 210, beat: 'Finish under control.' },
    ],
  },
  {
    id: 'lab-offset-slalom',
    name: 'Lab: Offset Slalom',
    summary: 'Flight lab: no-gravity offset gates for left-stick pitch/roll precision and D-pad recovery.',
    seed: 40002,
    startPosition: [0, 0, 180],
    medals: { gold: 34, silver: 48, bronze: 68 },
    design: {
      biome: 'open-claim-space',
      difficulty: 1,
      skillFocus: 'Stick shaping, roll/pitch response, and secondary strafe correction.',
      rhythm: ['left offset', 'right offset', 'high gate', 'low recover', 'finish'],
      generationPattern: 'Empty lab yard with wide offset gates and no gravity.',
    },
    field: {
      gateClearance: 330,
      routeCorridor: 420,
      gravityAnchorCount: 0,
      hazardBias: 'low',
      asteroidTuning: { PROCEDURAL_COUNT: 0 },
    },
    gates: [
      { id: 'lab-left', label: 'Left Offset', position: [-260, 60, -520], radius: 155, normal: [0.16, -0.04, 1], beat: 'Small roll and pitch inputs.' },
      { id: 'lab-right', label: 'Right Offset', position: [310, -40, -1120], radius: 155, normal: [-0.2, 0.03, 1], beat: 'Reverse the correction smoothly.' },
      { id: 'lab-high', label: 'High Gate', position: [120, 260, -1720], radius: 165, normal: [-0.05, -0.24, 1], beat: 'Use pitch before D-pad strafe.' },
      { id: 'lab-low', label: 'Low Recover', position: [-80, -220, -2300], radius: 170, normal: [0.06, 0.2, 1], beat: 'Recover with secondary strafe if needed.' },
      { id: 'lab-slalom-finish', label: 'Finish', position: [0, 0, -2900], radius: 190, beat: 'Settle the ship before finish.' },
    ],
  },
  {
    id: 'lab-soft-bend',
    name: 'Lab: Soft Bend',
    summary: 'Flight lab: one mild Dead Iron pull for comparing drift trajectory against commanded burn.',
    seed: 40003,
    startPosition: [0, 0, 180],
    medals: { gold: 42, silver: 58, bronze: 82 },
    design: {
      biome: 'open-claim-space',
      difficulty: 1,
      skillFocus: 'Trajectory/minimap reading and first gravity-aware brake tests.',
      rhythm: ['approach', 'soft pull', 'brake or burn', 'recover', 'finish'],
      generationPattern: 'One authored low-strength gravity anchor offset from a wide lab route.',
    },
    field: {
      gateClearance: 320,
      routeCorridor: 430,
      gravityAnchorCount: 1,
      hazardBias: 'low',
      asteroidTuning: { PROCEDURAL_COUNT: 0 },
      gravityAnchors: [
        { id: 'lab-soft-anchor', position: [470, -100, -1420], radius: 140, massScale: 0.18, visualIntensity: 0.72 },
      ],
    },
    gates: [
      { id: 'lab-soft-entry', label: 'Entry', position: [0, 0, -520], radius: 160, beat: 'Enter normally.' },
      { id: 'lab-soft-approach', label: 'Approach', position: [250, -40, -1120], radius: 165, normal: [-0.16, 0.02, 1], beat: 'Watch the drift line bend.' },
      { id: 'lab-soft-arc', label: 'Arc', position: [360, -130, -1760], radius: 175, normal: [-0.18, 0.08, 1], beat: 'Compare coast against burn.' },
      { id: 'lab-soft-finish', label: 'Finish', position: [0, 0, -2460], radius: 205, beat: 'Exit with speed under control.' },
    ],
  },
  {
    id: 'lab-hook-exit',
    name: 'Lab: Hook Exit',
    summary: 'Flight lab: one stronger hook to tune well-exit assist and controller recovery.',
    seed: 40004,
    startPosition: [0, 0, 180],
    medals: { gold: 44, silver: 62, bronze: 88 },
    design: {
      biome: 'open-claim-space',
      difficulty: 2,
      skillFocus: 'Gravity hook entry, exit thrust, and recovery from a strong pull.',
      rhythm: ['wide setup', 'hook', 'exit burn', 'settle', 'finish'],
      generationPattern: 'Single moderate anchor outside a wide gate bubble.',
    },
    field: {
      gateClearance: 300,
      routeCorridor: 400,
      gravityAnchorCount: 1,
      hazardBias: 'low',
      asteroidTuning: { PROCEDURAL_COUNT: 0 },
      gravityAnchors: [
        { id: 'lab-hook-anchor', position: [690, -120, -1500], radius: 155, massScale: 0.28, visualIntensity: 0.84 },
      ],
    },
    gates: [
      { id: 'lab-hook-entry', label: 'Hook Entry', position: [0, 20, -520], radius: 155, beat: 'Build speed before setup.' },
      { id: 'lab-hook-setup', label: 'Wide Setup', position: [520, -80, -1140], radius: 165, normal: [-0.34, 0.06, 1], beat: 'Pass wide of the anchor.' },
      { id: 'lab-hook-exit-gate', label: 'Exit Burn', position: [220, -180, -1840], radius: 175, normal: [0.18, 0.12, 1], beat: 'Burn out after the pull catches.' },
      { id: 'lab-hook-finish', label: 'Finish', position: [0, 0, -2580], radius: 205, beat: 'Settle the line.' },
    ],
  },
  {
    id: 'lab-speed-recover',
    name: 'Lab: Speed Recover',
    summary: 'Flight lab: high-speed offset finish for boost readability, braking, and overspeed recovery.',
    seed: 40005,
    startPosition: [0, 0, 180],
    medals: { gold: 36, silver: 52, bronze: 76 },
    design: {
      biome: 'open-claim-space',
      difficulty: 2,
      skillFocus: 'Boost steering readability, speed assist, and late-line recovery.',
      rhythm: ['long burn', 'late offset', 'brake check', 'finish'],
      generationPattern: 'Long empty burn lane with a late offset gate.',
    },
    field: {
      gateClearance: 360,
      routeCorridor: 460,
      gravityAnchorCount: 0,
      hazardBias: 'low',
      asteroidTuning: { PROCEDURAL_COUNT: 0 },
    },
    gates: [
      { id: 'lab-speed-burn', label: 'Burn', position: [0, 0, -720], radius: 170, beat: 'Build speed.' },
      { id: 'lab-speed-commit', label: 'Commit', position: [0, 0, -1600], radius: 170, beat: 'Boost through the gap.' },
      { id: 'lab-speed-offset', label: 'Late Offset', position: [420, 160, -2440], radius: 190, normal: [-0.24, -0.1, 1], beat: 'Release boost and recover.' },
      { id: 'lab-speed-finish', label: 'Finish', position: [0, 0, -3180], radius: 220, beat: 'Brake only as much as needed.' },
    ],
  },
  {
    id: 'training-clear-line',
    name: 'Clear Line',
    summary: 'Training 01: open space, oversized gates, and the basic launch line.',
    seed: 41010,
    startPosition: [0, 0, 180],
    medals: { gold: 28, silver: 42, bronze: 62 },
    tutorial: {
      trainingOrder: 1,
      lessonTitle: 'Basic thrust and gate order',
      lessonSummary: 'Fly forward through the green gates. No rocks, no gravity, just the line.',
      tipTriggers: {
        start: 'Push left stick up or hold W to thrust forward. Aim for the green gate.',
        gates: {
          0: 'Good. Gates must be flown in order.',
          1: 'Use small stick movements. Smooth beats hard turns.',
          2: 'Last gate is the finish. Keep the nose steady.',
        },
      },
    },
    design: {
      biome: 'open-claim-space',
      difficulty: 1,
      skillFocus: 'Forward thrust, basic steering, and ordered checkpoint reading.',
      rhythm: ['straight launch', 'steady aim', 'minor pitch correction', 'finish line'],
      generationPattern: 'Empty training lane with no procedural asteroids and no gravity anchors.',
    },
    field: {
      gateClearance: 360,
      routeCorridor: 420,
      gravityAnchorCount: 0,
      hazardBias: 'low',
      asteroidTuning: {
        PROCEDURAL_COUNT: 0,
      },
    },
    gates: [
      { id: 'first-light', label: 'First Light', position: [0, 0, -420], radius: 150, beat: 'Teach forward thrust and the green required gate.' },
      { id: 'steady-line', label: 'Steady Line', position: [0, 60, -900], radius: 150, beat: 'Hold a straight controlled line.' },
      { id: 'trim-check', label: 'Trim Check', position: [80, 20, -1360], radius: 155, beat: 'Add a tiny correction without oversteering.' },
      { id: 'clear-finish', label: 'Clear Finish', position: [0, 0, -1820], radius: 170, beat: 'Finish clean in empty space.' },
    ],
  },
  {
    id: 'training-drift-yard',
    name: 'Drift Yard',
    summary: 'Training 02: wide offset gates for steering, brake, strafe, and camera confidence.',
    seed: 41020,
    startPosition: [0, 0, 180],
    medals: { gold: 38, silver: 54, bronze: 78 },
    tutorial: {
      trainingOrder: 2,
      lessonTitle: 'Correcting drift',
      lessonSummary: 'Use pitch, roll, reverse, and strafe to recover from gentle offsets.',
      tipTriggers: {
        start: 'Right stick steers. Pull left stick down or hold S to slow and back up.',
        gates: {
          0: 'Next gate is offset. Roll and pitch before you need them.',
          1: 'D-pad or Space/Ctrl strafes without turning the nose.',
          2: 'Y or C toggles camera if the view feels wrong.',
          3: 'Brake early if you overshoot. Recovery is part of racing.',
        },
      },
    },
    design: {
      biome: 'open-claim-space',
      difficulty: 1,
      skillFocus: 'Pitch, roll, reverse thrust, strafe, and basic recovery.',
      rhythm: ['forward launch', 'left offset', 'high correction', 'right drift', 'low finish'],
      generationPattern: 'Empty yard lane with wide offset gates and no gravity or collision hazards.',
    },
    field: {
      gateClearance: 340,
      routeCorridor: 420,
      gravityAnchorCount: 0,
      hazardBias: 'low',
      asteroidTuning: {
        PROCEDURAL_COUNT: 0,
      },
    },
    gates: [
      { id: 'yard-entry', label: 'Yard Entry', position: [0, 20, -420], radius: 145, beat: 'Confirm launch again.' },
      { id: 'left-drift', label: 'Left Drift', position: [-340, 80, -940], radius: 150, normal: [0.28, -0.05, 1], beat: 'Introduce a gentle left correction.' },
      { id: 'high-trim', label: 'High Trim', position: [-120, 300, -1440], radius: 155, normal: [0.1, -0.35, 1], beat: 'Teach vertical correction.' },
      { id: 'right-drift', label: 'Right Drift', position: [360, 120, -1900], radius: 150, normal: [-0.32, -0.05, 1], beat: 'Recover across the route.' },
      { id: 'yard-finish', label: 'Yard Finish', position: [0, -80, -2380], radius: 170, beat: 'Finish after a soft downward correction.' },
    ],
  },
  {
    id: 'training-boost-run',
    name: 'Boost Run',
    summary: 'Training 03: long safe gaps that make boost useful without making it mandatory.',
    seed: 41030,
    startPosition: [0, 0, 180],
    medals: { gold: 44, silver: 62, bronze: 88 },
    tutorial: {
      trainingOrder: 3,
      lessonTitle: 'Boost and energy rhythm',
      lessonSummary: 'Use bumpers or Shift to boost on long straights, then recover before the next turn.',
      tipTriggers: {
        start: 'Hold LB/RB or Shift while thrusting to boost.',
        gates: {
          0: 'Boost drains energy. Release it before you need control.',
          1: 'Long gaps are burn lanes. Short gaps are for aiming.',
          2: 'If you overshoot, brake and reset the nose.',
        },
      },
    },
    design: {
      biome: 'open-claim-space',
      difficulty: 1,
      skillFocus: 'Boost timing, energy awareness, overshoot recovery, and long-line confidence.',
      rhythm: ['launch burn', 'long straight', 'gentle bend', 'second burn', 'finish'],
      generationPattern: 'Very sparse open claim background far outside the route corridor.',
    },
    field: {
      gateClearance: 290,
      routeCorridor: 360,
      gravityAnchorCount: 0,
      hazardBias: 'low',
      asteroidTuning: {
        PROCEDURAL_COUNT: 70,
        SPHERE_INNER: 1700,
        SPHERE_OUTER: 4800,
        RADIUS_RANGE: 115,
        MASS_COEF: 5.2,
        CORE_DENSITY_RANGE: 0.45,
        DRIFT_RANGE: 0.12,
      },
    },
    gates: [
      { id: 'burn-lane', label: 'Burn Lane', position: [0, 0, -520], radius: 135, beat: 'First boost lane.' },
      { id: 'long-burn', label: 'Long Burn', position: [0, 40, -1340], radius: 140, beat: 'Let boost build speed in a safe gap.' },
      { id: 'ease-right', label: 'Ease Right', position: [360, 120, -2020], radius: 145, normal: [-0.32, -0.08, 1], beat: 'Release boost and aim before the bend.' },
      { id: 'second-burn', label: 'Second Burn', position: [220, 40, -2860], radius: 145, normal: [0.08, 0, 1], beat: 'Another safe burn lane.' },
      { id: 'boost-finish', label: 'Boost Finish', position: [0, 0, -3520], radius: 170, beat: 'Finish with speed under control.' },
    ],
  },
  {
    id: 'training-soft-pull',
    name: 'Soft Pull',
    summary: 'Training 04: one readable heavy rock gently bends the route and minimap line.',
    seed: 41040,
    startPosition: [0, 0, 180],
    medals: { gold: 54, silver: 74, bronze: 104 },
    tutorial: {
      trainingOrder: 4,
      lessonTitle: 'Reading gravity',
      lessonSummary: 'Watch the trajectory and minimap bend near a mild Dead Iron anchor.',
      tipTriggers: {
        start: 'The hologram/minimap shows your future path.',
        gates: {
          0: 'That heavy rock will pull your line. Do not fight too early.',
          1: 'Skim wide first. Close passes get faster later.',
          2: 'Use reverse thrust if the pull carries you long.',
        },
        proximity: [
          { anchorId: 'yard-anchor', range: 760, text: 'Feel that pull? Aim ahead of the gate, not at the rock.' },
        ],
      },
    },
    design: {
      biome: 'open-claim-space',
      difficulty: 1,
      skillFocus: 'Trajectory/minimap reading and first gentle gravity correction.',
      rhythm: ['clean launch', 'approach heavy rock', 'soft bend', 'wide recovery', 'finish'],
      generationPattern: 'Sparse open claim field with one authored low-strength Dead Iron anchor offset from the route.',
    },
    field: {
      gateClearance: 280,
      routeCorridor: 360,
      gravityAnchorCount: 1,
      hazardBias: 'low',
      asteroidTuning: {
        PROCEDURAL_COUNT: 90,
        SPHERE_INNER: 1850,
        SPHERE_OUTER: 5200,
        RADIUS_RANGE: 120,
        MASS_COEF: 5.6,
        CORE_DENSITY_RANGE: 0.5,
        DRIFT_RANGE: 0.12,
      },
      gravityAnchors: [
        { id: 'yard-anchor', position: [520, -140, -1560], radius: 130, massScale: 0.16, visualIntensity: 0.72 },
      ],
    },
    gates: [
      { id: 'pull-entry', label: 'Pull Entry', position: [0, 20, -500], radius: 135, beat: 'Start from a normal line.' },
      { id: 'well-approach', label: 'Well Approach', position: [260, -30, -1160], radius: 145, normal: [-0.18, 0.03, 1], beat: 'Line up wide of the anchor.' },
      { id: 'soft-arc', label: 'Soft Arc', position: [360, -120, -1900], radius: 150, normal: [-0.22, 0.08, 1], beat: 'Let the anchor bend the path gently.' },
      { id: 'wide-recover', label: 'Wide Recover', position: [-120, 20, -2500], radius: 155, normal: [0.24, -0.02, 1], beat: 'Recover after the pull.' },
      { id: 'pull-finish', label: 'Pull Finish', position: [0, 0, -3140], radius: 175, beat: 'Finish after a gravity-assisted bend.' },
    ],
  },
  {
    id: 'training-hook-pass',
    name: 'Hook Pass',
    summary: 'Training 05: two safe Dead Iron hooks introduce gravity-assisted turns.',
    seed: 41050,
    startPosition: [0, 0, 180],
    medals: { gold: 66, silver: 88, bronze: 122 },
    tutorial: {
      trainingOrder: 5,
      lessonTitle: 'Using gravity to turn',
      lessonSummary: 'Let heavy rocks help bend the ship instead of burning all speed away.',
      tipTriggers: {
        start: 'Fast line: pass wide, let gravity hook you, then thrust out.',
        gates: {
          0: 'Set up outside the first rock before the turn.',
          1: 'Now burn out of the hook. Do not stare at the rock.',
          2: 'Second hook is the same idea from the other side.',
          3: 'Gravity turns are faster when you exit clean.',
        },
        proximity: [
          { anchorId: 'left-hook', range: 820, text: 'First hook: let the pull start the turn, then boost out.' },
          { anchorId: 'right-hook', range: 820, text: 'Second hook: aim past the rock and trust the arc.' },
        ],
      },
    },
    design: {
      biome: 'open-claim-space',
      difficulty: 2,
      skillFocus: 'Safe gravity-assisted bends and exit thrust before the main racing courses.',
      rhythm: ['launch setup', 'left hook', 'exit burn', 'right hook', 'home burn'],
      generationPattern: 'Sparse field with two authored moderate anchors outside wide gate bubbles.',
    },
    field: {
      gateClearance: 260,
      routeCorridor: 330,
      gravityAnchorCount: 2,
      hazardBias: 'low',
      asteroidTuning: {
        PROCEDURAL_COUNT: 120,
        SPHERE_INNER: 1650,
        SPHERE_OUTER: 5600,
        RADIUS_RANGE: 135,
        MASS_COEF: 6.4,
        CORE_DENSITY_RANGE: 0.62,
        DRIFT_RANGE: 0.16,
      },
      gravityAnchors: [
        { id: 'left-hook', position: [680, -120, -1380], radius: 145, massScale: 0.22, visualIntensity: 0.78 },
        { id: 'right-hook', position: [-720, 170, -2580], radius: 150, massScale: 0.24, visualIntensity: 0.82 },
      ],
    },
    gates: [
      { id: 'hook-entry', label: 'Hook Entry', position: [0, 40, -520], radius: 130, beat: 'Build speed before the first hook.' },
      { id: 'left-setup', label: 'Left Setup', position: [470, -80, -1120], radius: 140, normal: [-0.35, 0.06, 1], beat: 'Set up outside the first anchor.' },
      { id: 'left-exit', label: 'Left Exit', position: [210, -180, -1840], radius: 145, normal: [0.16, 0.12, 1], beat: 'Exit the first gravity hook.' },
      { id: 'right-setup', label: 'Right Setup', position: [-500, 120, -2380], radius: 145, normal: [0.42, -0.12, 1], beat: 'Set up the second anchor from the other side.' },
      { id: 'right-exit', label: 'Right Exit', position: [-260, 240, -3060], radius: 150, normal: [-0.14, -0.16, 1], beat: 'Exit clean from the second hook.' },
      { id: 'hook-finish', label: 'Hook Finish', position: [0, 0, -3740], radius: 178, beat: 'Finish ready for Claim Shakedown.' },
    ],
  },
  {
    id: 'claim-shakedown',
    name: 'Claim Shakedown',
    summary: 'A short league qualifier through the open field and back to the base beacon.',
    seed: 10100,
    startPosition: [0, 0, 180],
    medals: { gold: 46, silver: 58, bronze: 74 },
    design: {
      biome: 'open-claim-space',
      difficulty: 1,
      skillFocus: 'Basic gate reading, boost timing, and gentle recovery arcs.',
      rhythm: ['straight launch', 'wide high setup', 'easy lateral correction', 'clean return'],
      generationPattern: 'Sparse open-claim shell with wide gate bubbles and only mild gravity near the intended route.',
    },
    field: {
      gateClearance: 190,
      routeCorridor: 220,
      gravityAnchorCount: 0,
      hazardBias: 'low',
      asteroidTuning: {
        PROCEDURAL_COUNT: 520,
        SPHERE_OUTER: 4200,
        RADIUS_RANGE: 165,
        MASS_COEF: 9.5,
        CORE_DENSITY_RANGE: 1.2,
      },
    },
    gates: [
      { id: 'launch-slot', label: 'Launch Slot', position: [0, 40, -480], radius: 96, beat: 'Confirm forward launch and first gate read.' },
      { id: 'high-line', label: 'High Line', position: [360, 170, -980], radius: 92, normal: [-0.35, -0.1, 1], beat: 'Teach a high, soft correction without heavy gravity.' },
      { id: 'belter-turn', label: 'Belter Turn', position: [-240, -80, -1420], radius: 88, normal: [0.4, 0.1, 1], beat: 'Introduce lateral route planning.' },
      { id: 'base-return', label: 'Base Return', position: [0, 0, 110], radius: 108, beat: 'Finish on a forgiving home-line target.' },
    ],
  },
  {
    id: 'dead-iron-sweep',
    name: 'Dead Iron Sweep',
    summary: 'A mid-field race built around fast bends near heavier wells.',
    seed: 20420,
    startPosition: [0, 0, 180],
    medals: { gold: 82, silver: 104, bronze: 132 },
    design: {
      biome: 'dead-iron-belt',
      difficulty: 3,
      skillFocus: 'Committed slingshot bends and quick recovery after gravity-assisted turns.',
      rhythm: ['yard exit', 'hard sweep right', 'long falling line', 'cross-field drift', 'return burn', 'finish'],
      generationPattern: 'Medium-dense Dead Iron belt with stronger wells outside bend exits and moderate route-corridor pressure.',
    },
    field: {
      gateClearance: 170,
      routeCorridor: 175,
      gravityAnchorCount: 2,
      hazardBias: 'medium',
      asteroidTuning: {
        PROCEDURAL_COUNT: 820,
        SPHERE_OUTER: 6500,
        RADIUS_RANGE: 225,
        MASS_COEF: 12.5,
        CORE_DENSITY_RANGE: 1.7,
        SIZE_INNER_MAX: 0.52,
      },
    },
    gates: [
      { id: 'yard-exit', label: 'Yard Exit', position: [-180, 60, -680], radius: 96, beat: 'Move out of the launch lane into belt traffic.' },
      { id: 'iron-hook', label: 'Iron Hook', position: [760, -160, -1520], radius: 92, normal: [-0.5, 0.1, 1], beat: 'First real gravity-assisted hook.' },
      { id: 'long-fall', label: 'Long Fall', position: [260, 360, -2600], radius: 98, normal: [0.1, -0.3, 1], beat: 'Hold speed through a longer falling section.' },
      { id: 'cross-drift', label: 'Cross Drift', position: [-840, 120, -2360], radius: 96, normal: [0.7, -0.1, 1], beat: 'Cross the field without bleeding too much speed.' },
      { id: 'return-burn', label: 'Return Burn', position: [-420, -140, -780], radius: 92, normal: [0.45, 0.1, -1], beat: 'Recover from the cross-field drift and line up the finish.' },
      { id: 'league-line', label: 'League Line', position: [0, 0, 120], radius: 110, beat: 'Fast home-line finish.' },
    ],
  },
  {
    id: 'black-core-run',
    name: 'Black Core Run',
    summary: 'A deep-field sprint where close gravity passes are faster than clean lines.',
    seed: 31990,
    startPosition: [0, 0, 180],
    medals: { gold: 138, silver: 172, bronze: 218 },
    design: {
      biome: 'black-core-field',
      difficulty: 4,
      skillFocus: 'Reading large gravity wells without requiring a near-perfect capture line.',
      rhythm: ['deep launch', 'wide left setup', 'controlled sink', 'knife-edge pass', 'core-side return', 'snapback', 'home burn'],
      generationPattern: 'Large deep-field wells with wider gate bubbles than an expert course and fewer inner-shell hazards.',
    },
    field: {
      gateClearance: 210,
      routeCorridor: 210,
      gravityAnchorCount: 3,
      hazardBias: 'medium',
      asteroidTuning: {
        PROCEDURAL_COUNT: 860,
        SPHERE_OUTER: 7800,
        RADIUS_RANGE: 245,
        RADIAL_BIAS: 0.84,
        SIZE_INNER_MAX: 0.48,
        MASS_COEF: 13.2,
        CORE_DENSITY_MIN: 0.78,
        CORE_DENSITY_RANGE: 1.55,
        DRIFT_RANGE: 0.28,
      },
    },
    gates: [
      { id: 'deep-ticket', label: 'Deep Ticket', position: [120, -80, -760], radius: 104, beat: 'Leave the yard with more room than the old expert opening.' },
      { id: 'hard-left', label: 'Hard Left', position: [960, 220, -1680], radius: 104, normal: [-0.48, -0.12, 1], beat: 'A wide, readable setup for the first major bend.' },
      { id: 'sinkhole', label: 'Sinkhole', position: [560, -340, -3040], radius: 104, normal: [-0.18, 0.38, 1], beat: 'Use the well, but do not require a razor-thin drop.' },
      { id: 'knife-edge', label: 'Knife Edge', position: [-820, -90, -3500], radius: 100, normal: [0.62, 0.04, 1], beat: 'Keep the scary pass, with more margin and less depth.' },
      { id: 'dead-core', label: 'Dead Core', position: [-1120, 450, -2260], radius: 104, normal: [0.46, -0.25, -1], beat: 'Return around the core without forcing maximum gravity exposure.' },
      { id: 'snapback', label: 'Snapback', position: [-360, 150, -1060], radius: 104, normal: [0.28, -0.05, -1], beat: 'Let players recover before the final burn.' },
      { id: 'home-burn', label: 'Home Burn', position: [0, 0, 125], radius: 116, beat: 'Larger finish gate for high-speed arrivals.' },
    ],
  },
];

function legacyCourse(id: string): AuthoredRaceCourse {
  const course = LEGACY_RACE_COURSES.find((candidate) => candidate.id === id);
  if (!course) throw new Error(`Missing legacy race course: ${id}`);
  return course;
}

const CLAIM_SHAKEDOWN = legacyCourse('claim-shakedown');

export const ARCHIVED_RACE_COURSES: readonly AuthoredRaceCourse[] = LEGACY_RACE_COURSES.filter(
  (course) => course.id !== CLAIM_SHAKEDOWN.id,
);

export const AUTHORED_RACE_COURSES: readonly AuthoredRaceCourse[] = [
  CLAIM_SHAKEDOWN,
  {
    id: 'claim-highline',
    name: 'Claim Highline',
    summary: 'A Claim Shakedown variant that climbs above the yard before diving home.',
    seed: 10110,
    startPosition: [0, 0, 180],
    medals: { gold: 54, silver: 68, bronze: 88 },
    design: {
      biome: 'open-claim-space',
      difficulty: 1,
      skillFocus: 'Readable vertical routing, boost timing, and a controlled home dive.',
      rhythm: ['launch', 'high climb', 'crest', 'downward trim', 'home line'],
      generationPattern: 'Sparse open-claim shell with Shakedown-style clearance and a taller route profile.',
    },
    field: {
      gateClearance: 210,
      routeCorridor: 250,
      gravityAnchorCount: 0,
      hazardBias: 'low',
      asteroidTuning: {
        PROCEDURAL_COUNT: 620,
        SPHERE_OUTER: 4700,
        RADIUS_RANGE: 170,
        MASS_COEF: 9.2,
        CORE_DENSITY_RANGE: 1.15,
        DRIFT_RANGE: 0.24,
      },
    },
    gates: [
      { id: 'highline-launch', label: 'Launch Slot', position: [0, 60, -520], radius: 102, beat: 'Leave the yard on a familiar line.' },
      { id: 'highline-rise', label: 'High Rise', position: [260, 520, -1060], radius: 100, normal: [-0.22, -0.46, 1], beat: 'Pitch up into the vertical route.' },
      { id: 'highline-crest', label: 'Crest Marker', position: [-180, 760, -1620], radius: 104, normal: [0.18, -0.54, 1], beat: 'Hold speed over the top.' },
      { id: 'highline-drop', label: 'Drop Trim', position: [-420, 260, -820], radius: 102, normal: [0.42, -0.18, -1], beat: 'Start the dive without bleeding all speed.' },
      { id: 'highline-home', label: 'Home Line', position: [0, 0, 120], radius: 116, beat: 'Dive back through the claim beacon.' },
    ],
  },
  {
    id: 'claim-crosswind',
    name: 'Claim Crosswind',
    summary: 'A Claim Shakedown variant with a broader lateral sweep across the open field.',
    seed: 10120,
    startPosition: [0, 0, 180],
    medals: { gold: 58, silver: 74, bronze: 96 },
    design: {
      biome: 'open-claim-space',
      difficulty: 2,
      skillFocus: 'Wide lateral planning, roll confidence, and fast course correction.',
      rhythm: ['launch', 'left sweep', 'right commit', 'cross-field return', 'finish'],
      generationPattern: 'Open claim field with wider lateral spread and mild route pressure.',
    },
    field: {
      gateClearance: 205,
      routeCorridor: 245,
      gravityAnchorCount: 0,
      hazardBias: 'low',
      asteroidTuning: {
        PROCEDURAL_COUNT: 680,
        SPHERE_OUTER: 5200,
        RADIUS_RANGE: 180,
        MASS_COEF: 9.8,
        CORE_DENSITY_RANGE: 1.2,
        DRIFT_RANGE: 0.28,
      },
    },
    gates: [
      { id: 'crosswind-launch', label: 'Launch Slot', position: [0, 40, -500], radius: 100, beat: 'Use the Shakedown launch read.' },
      { id: 'crosswind-left', label: 'Left Claim', position: [-620, 120, -1040], radius: 100, normal: [0.54, -0.08, 1], beat: 'Commit left without over-rotating.' },
      { id: 'crosswind-right', label: 'Right Claim', position: [720, -140, -1560], radius: 98, normal: [-0.58, 0.1, 1], beat: 'Cut across the field at speed.' },
      { id: 'crosswind-return', label: 'Return Slot', position: [360, 120, -620], radius: 102, normal: [-0.3, -0.08, -1], beat: 'Reverse the line back toward home.' },
      { id: 'crosswind-home', label: 'Home Line', position: [0, 0, 115], radius: 116, beat: 'Finish on the beacon.' },
    ],
  },
  {
    id: 'claim-iron-hook',
    name: 'Claim Iron Hook',
    summary: 'A Claim Shakedown variant with one gentle Dead Iron body shaping the turn.',
    seed: 10130,
    startPosition: [0, 0, 180],
    medals: { gold: 62, silver: 80, bronze: 104 },
    design: {
      biome: 'open-claim-space',
      difficulty: 2,
      skillFocus: 'One readable gravity-assisted bend without leaving starter-course readability.',
      rhythm: ['launch', 'wide setup', 'soft hook', 'exit burn', 'home line'],
      generationPattern: 'Shakedown-style open field with one authored Dead Iron anchor outside the route.',
    },
    field: {
      gateClearance: 220,
      routeCorridor: 270,
      gravityAnchorCount: 1,
      hazardBias: 'low',
      asteroidTuning: {
        PROCEDURAL_COUNT: 720,
        SPHERE_OUTER: 5400,
        RADIUS_RANGE: 185,
        MASS_COEF: 9.6,
        CORE_DENSITY_RANGE: 1.25,
        DRIFT_RANGE: 0.24,
      },
      gravityAnchors: [
        { id: 'claim-hook-anchor', position: [720, -120, -1320], radius: 150, massScale: 0.18, visualIntensity: 0.76 },
      ],
    },
    gates: [
      { id: 'iron-hook-launch', label: 'Launch Slot', position: [0, 40, -500], radius: 104, beat: 'Start from the familiar lane.' },
      { id: 'iron-hook-setup', label: 'Wide Setup', position: [430, -60, -980], radius: 104, normal: [-0.38, 0.06, 1], beat: 'Pass wide of the Dead Iron body.' },
      { id: 'iron-hook-apex', label: 'Hook Apex', position: [300, -180, -1640], radius: 106, normal: [-0.18, 0.12, 1], beat: 'Let the gravity bend help.' },
      { id: 'iron-hook-exit', label: 'Exit Burn', position: [-360, -20, -1060], radius: 106, normal: [0.36, 0.02, -1], beat: 'Burn out before the turn dies.' },
      { id: 'iron-hook-home', label: 'Home Line', position: [0, 0, 120], radius: 118, beat: 'Bring the hooked line home.' },
    ],
  },
  {
    id: 'claim-traverse',
    name: 'Claim Traverse',
    summary: 'A large point-to-point sprint across the whole claim field.',
    seed: 10200,
    startPosition: [0, 0, 360],
    medals: { gold: 210, silver: 270, bronze: 360 },
    design: {
      biome: 'dead-iron-belt',
      difficulty: 3,
      skillFocus: 'Long-distance route judgment, sustained speed, recovery, and gravity-assisted navigation.',
      rhythm: ['deep launch', 'open burn', 'field crossing', 'iron bend', 'far claim', 'finish beacon'],
      generationPattern: 'Very large open traverse with high asteroid count, wide gate beacons, and authored heavy bodies as route landmarks.',
    },
    field: {
      gateClearance: 360,
      routeCorridor: 540,
      gravityAnchorCount: 4,
      hazardBias: 'medium',
      asteroidTuning: {
        PROCEDURAL_COUNT: 900,
        VISUAL_COUNT: 5600,
        SPHERE_INNER: 700,
        SPHERE_OUTER: 30000,
        RADIUS_MIN: 8,
        RADIUS_RANGE: 230,
        RADIUS_POWER: 1.42,
        VISUAL_RADIUS_MIN: 12,
        VISUAL_RADIUS_RANGE: 180,
        VISUAL_RADIUS_POWER: 1.72,
        RADIAL_BIAS: 0.72,
        SIZE_INNER_MAX: 0.28,
        MASS_COEF: 7.2,
        CORE_DENSITY_MIN: 0.5,
        CORE_DENSITY_RANGE: 1.15,
        DRIFT_MIN: 0.02,
        DRIFT_RANGE: 0.14,
      },
      gravityAnchors: [
        { id: 'traverse-near-iron', position: [1180, 220, -3600], radius: 210, massScale: 0.16, visualIntensity: 0.76 },
        { id: 'traverse-cross-iron', position: [-2100, -360, -8600], radius: 260, massScale: 0.2, visualIntensity: 0.82 },
        { id: 'traverse-far-iron', position: [2600, 520, -14200], radius: 310, massScale: 0.24, visualIntensity: 0.9 },
        { id: 'traverse-home-iron', position: [-1600, -240, -20500], radius: 280, massScale: 0.18, visualIntensity: 0.84 },
      ],
    },
    gates: [
      { id: 'traverse-launch', label: 'Claim Exit', position: [0, 80, -920], radius: 170, beat: 'Leave the yard and choose a fast outbound line.' },
      { id: 'traverse-first-burn', label: 'First Burn', position: [860, 280, -3300], radius: 185, normal: [-0.22, -0.06, 1], beat: 'Build speed across open claim space.' },
      { id: 'traverse-crossing', label: 'Crossing Buoy', position: [-1550, -320, -7200], radius: 210, normal: [0.48, 0.08, 1], beat: 'Commit across the dense field.' },
      { id: 'traverse-iron-bend', label: 'Iron Bend', position: [2050, 520, -11800], radius: 220, normal: [-0.5, -0.12, 1], beat: 'Use the far Dead Iron as a route landmark.' },
      { id: 'traverse-far-claim', label: 'Far Claim', position: [-2200, -240, -16800], radius: 235, normal: [0.55, 0.04, 1], beat: 'Recover after the long bend.' },
      { id: 'traverse-final-burn', label: 'Final Burn', position: [900, 160, -21400], radius: 245, normal: [-0.3, -0.02, 1], beat: 'Hold the final high-speed line.' },
      { id: 'traverse-finish', label: 'Finish Beacon', position: [0, 0, -24800], radius: 280, beat: 'Point-to-point finish across the map.' },
    ],
  },
  {
    id: 'far-wake-run',
    name: 'Far Wake Run',
    summary: 'A long outbound burn with small course corrections and distant Dead Iron landmarks.',
    seed: 10220,
    startPosition: [0, 0, 360],
    medals: { gold: 198, silver: 255, bronze: 340 },
    design: {
      biome: 'dead-iron-belt',
      difficulty: 3,
      skillFocus: 'Sustained speed, small corrections, and choosing when not to oversteer across a huge field.',
      rhythm: ['launch burn', 'wake marker', 'wide drift', 'iron skim', 'far beacon'],
      generationPattern: 'Large point-to-point wake with a straighter profile, broad visual density, and sparse real hazards around the route.',
    },
    field: {
      gateClearance: 380,
      routeCorridor: 600,
      gravityAnchorCount: 3,
      hazardBias: 'medium',
      asteroidTuning: {
        PROCEDURAL_COUNT: 860,
        VISUAL_COUNT: 5400,
        SPHERE_INNER: 700,
        SPHERE_OUTER: 28500,
        RADIUS_MIN: 8,
        RADIUS_RANGE: 220,
        RADIUS_POWER: 1.48,
        VISUAL_RADIUS_MIN: 10,
        VISUAL_RADIUS_RANGE: 170,
        VISUAL_RADIUS_POWER: 1.72,
        RADIAL_BIAS: 0.76,
        SIZE_INNER_MAX: 0.28,
        MASS_COEF: 7,
        CORE_DENSITY_MIN: 0.5,
        CORE_DENSITY_RANGE: 1.12,
        DRIFT_MIN: 0.02,
        DRIFT_RANGE: 0.12,
      },
      gravityAnchors: [
        { id: 'wake-left-iron', position: [-980, 260, -5200], radius: 220, massScale: 0.14, visualIntensity: 0.76 },
        { id: 'wake-right-iron', position: [1440, -180, -11800], radius: 290, massScale: 0.18, visualIntensity: 0.84 },
        { id: 'wake-far-iron', position: [-1180, 420, -19000], radius: 260, massScale: 0.16, visualIntensity: 0.8 },
      ],
    },
    gates: [
      { id: 'wake-exit', label: 'Claim Exit', position: [0, 70, -900], radius: 175, beat: 'Start with a clean outbound burn.' },
      { id: 'wake-marker', label: 'Wake Marker', position: [-520, 180, -4300], radius: 195, normal: [0.16, -0.04, 1], beat: 'Make one small correction, then hold speed.' },
      { id: 'wake-drift', label: 'Long Drift', position: [820, -120, -8800], radius: 220, normal: [-0.28, 0.03, 1], beat: 'Let the ship cross the wake without fighting it.' },
      { id: 'wake-iron-skim', label: 'Iron Skim', position: [1220, 220, -14000], radius: 230, normal: [-0.22, -0.04, 1], beat: 'Skim the right-side landmark and keep the nose calm.' },
      { id: 'wake-far-burn', label: 'Far Burn', position: [-520, 120, -20200], radius: 250, normal: [0.26, -0.02, 1], beat: 'Correct back toward the far beacon.' },
      { id: 'wake-finish', label: 'Wake Finish', position: [0, 0, -23800], radius: 285, beat: 'Finish after a sustained open-field run.' },
    ],
  },
  {
    id: 'iron-meridian',
    name: 'Iron Meridian',
    summary: 'A tall traverse that climbs above the claim plane before diving through a far meridian beacon.',
    seed: 10240,
    startPosition: [0, 0, 360],
    medals: { gold: 225, silver: 292, bronze: 386 },
    design: {
      biome: 'black-core-field',
      difficulty: 4,
      skillFocus: 'Long-course vertical routing, speed control on climbs, and recovering into a high-speed dive.',
      rhythm: ['yard exit', 'high climb', 'upper meridian', 'falling bend', 'low recovery', 'finish dive'],
      generationPattern: 'Large vertical point-to-point route with visual-only field density and authored Dead Iron bodies as climb/dive references.',
    },
    field: {
      gateClearance: 400,
      routeCorridor: 620,
      gravityAnchorCount: 5,
      hazardBias: 'medium',
      asteroidTuning: {
        PROCEDURAL_COUNT: 940,
        VISUAL_COUNT: 6200,
        SPHERE_INNER: 760,
        SPHERE_OUTER: 32000,
        RADIUS_MIN: 8,
        RADIUS_RANGE: 240,
        RADIUS_POWER: 1.46,
        VISUAL_RADIUS_MIN: 12,
        VISUAL_RADIUS_RANGE: 190,
        VISUAL_RADIUS_POWER: 1.68,
        RADIAL_BIAS: 0.74,
        SIZE_INNER_MAX: 0.3,
        MASS_COEF: 7.4,
        CORE_DENSITY_MIN: 0.55,
        CORE_DENSITY_RANGE: 1.22,
        DRIFT_MIN: 0.02,
        DRIFT_RANGE: 0.13,
      },
      gravityAnchors: [
        { id: 'meridian-lift-iron', position: [900, 1280, -4200], radius: 230, massScale: 0.14, visualIntensity: 0.78 },
        { id: 'meridian-high-iron', position: [-1320, 2600, -9200], radius: 320, massScale: 0.2, visualIntensity: 0.9 },
        { id: 'meridian-fall-iron', position: [2050, 1320, -14800], radius: 300, massScale: 0.22, visualIntensity: 0.88 },
        { id: 'meridian-low-iron', position: [-1680, -620, -20200], radius: 275, massScale: 0.18, visualIntensity: 0.82 },
        { id: 'meridian-final-iron', position: [620, -940, -25000], radius: 240, massScale: 0.15, visualIntensity: 0.78 },
      ],
    },
    gates: [
      { id: 'meridian-exit', label: 'Claim Exit', position: [0, 80, -980], radius: 180, beat: 'Leave the yard and start climbing.' },
      { id: 'meridian-lift', label: 'Lift Gate', position: [640, 920, -4200], radius: 205, normal: [-0.16, -0.3, 1], beat: 'Climb without killing forward speed.' },
      { id: 'meridian-upper', label: 'Upper Meridian', position: [-960, 2320, -9000], radius: 230, normal: [0.26, -0.38, 1], beat: 'Cross the high route marker.' },
      { id: 'meridian-fall', label: 'Falling Bend', position: [1480, 1280, -14200], radius: 235, normal: [-0.38, -0.18, 1], beat: 'Begin the long dive and use the landmark pull.' },
      { id: 'meridian-low', label: 'Low Recovery', position: [-1080, -480, -19800], radius: 250, normal: [0.42, 0.2, 1], beat: 'Recover below the claim plane.' },
      { id: 'meridian-final', label: 'Final Dive', position: [460, -760, -24600], radius: 265, normal: [-0.18, 0.22, 1], beat: 'Hold the fast dive to the far beacon.' },
      { id: 'meridian-finish', label: 'Meridian Finish', position: [0, 0, -28200], radius: 300, beat: 'Finish after the climb-and-dive route.' },
    ],
  },
  {
    id: 'blackglass-crossing',
    name: 'Blackglass Crossing',
    summary: 'A wide S-crossing through darker claim space with stronger landmark pulls.',
    seed: 10260,
    startPosition: [0, 0, 360],
    medals: { gold: 238, silver: 305, bronze: 405 },
    design: {
      biome: 'black-core-field',
      difficulty: 4,
      skillFocus: 'Wide lateral route choice, stronger gravity landmarks, and recovery from long cross-field arcs.',
      rhythm: ['claim exit', 'left crossing', 'right sweep', 'blackglass bend', 'counter-cross', 'finish slot'],
      generationPattern: 'Large S-shaped crossing with dense visual-only field fill and stronger authored Dead Iron bodies outside gate bubbles.',
    },
    field: {
      gateClearance: 390,
      routeCorridor: 580,
      gravityAnchorCount: 5,
      hazardBias: 'medium',
      asteroidTuning: {
        PROCEDURAL_COUNT: 980,
        VISUAL_COUNT: 6400,
        SPHERE_INNER: 760,
        SPHERE_OUTER: 33500,
        RADIUS_MIN: 9,
        RADIUS_RANGE: 250,
        RADIUS_POWER: 1.44,
        VISUAL_RADIUS_MIN: 12,
        VISUAL_RADIUS_RANGE: 200,
        VISUAL_RADIUS_POWER: 1.66,
        RADIAL_BIAS: 0.7,
        SIZE_INNER_MAX: 0.32,
        MASS_COEF: 7.6,
        CORE_DENSITY_MIN: 0.58,
        CORE_DENSITY_RANGE: 1.28,
        DRIFT_MIN: 0.02,
        DRIFT_RANGE: 0.14,
      },
      gravityAnchors: [
        { id: 'blackglass-left-iron', position: [-2450, -340, -5000], radius: 255, massScale: 0.17, visualIntensity: 0.82 },
        { id: 'blackglass-right-iron', position: [2700, 380, -10400], radius: 315, massScale: 0.22, visualIntensity: 0.9 },
        { id: 'blackglass-core-iron', position: [560, -820, -16000], radius: 350, massScale: 0.26, visualIntensity: 0.94 },
        { id: 'blackglass-counter-iron', position: [-2860, 620, -21400], radius: 290, massScale: 0.2, visualIntensity: 0.86 },
        { id: 'blackglass-finish-iron', position: [1200, -260, -26800], radius: 245, massScale: 0.16, visualIntensity: 0.8 },
      ],
    },
    gates: [
      { id: 'blackglass-exit', label: 'Claim Exit', position: [0, 80, -960], radius: 180, beat: 'Leave the yard and start the first crossing.' },
      { id: 'blackglass-left', label: 'Left Crossing', position: [-1980, -220, -5000], radius: 210, normal: [0.46, 0.04, 1], beat: 'Commit to the first wide left arc.' },
      { id: 'blackglass-right', label: 'Right Sweep', position: [2260, 300, -10100], radius: 225, normal: [-0.58, -0.08, 1], beat: 'Cross hard right and keep speed.' },
      { id: 'blackglass-core', label: 'Blackglass Bend', position: [700, -680, -15700], radius: 238, normal: [-0.08, 0.2, 1], beat: 'Pass near the darker core without getting swallowed.' },
      { id: 'blackglass-counter', label: 'Counter-Cross', position: [-2300, 520, -21100], radius: 248, normal: [0.48, -0.18, 1], beat: 'Use the counter landmark to bend back.' },
      { id: 'blackglass-slot', label: 'Finish Slot', position: [980, -140, -26400], radius: 265, normal: [-0.36, 0.02, 1], beat: 'Line up the last slot from the S-curve.' },
      { id: 'blackglass-finish', label: 'Crossing Finish', position: [0, 0, -29600], radius: 310, beat: 'Finish the wide crossing.' },
    ],
  },
];
