import type { AuthoredRaceCourse } from './courseAuthoring';

export const ARCHIVED_RACE_COURSES: readonly AuthoredRaceCourse[] = [];

export const AUTHORED_RACE_COURSES: readonly AuthoredRaceCourse[] = [
  {
    id: 'wake-primer',
    name: 'Wake Primer',
    summary: 'A shorter, flatter wake route that teaches asteroid checkpoints before Needle Wake.',
    seed: 13510,
    startPosition: [0, 0, 240],
    medals: { gold: 58, silver: 80, bronze: 112 },
    design: {
      biome: 'dead-iron-belt',
      difficulty: 2,
      skillFocus: 'Readable asteroid gates, gentle lift/drop movement, and clean exits without tight turns.',
      rhythm: ['launch ring', 'first wake', 'high marker', 'return stone', 'finish ring'],
      generationPattern: 'Needle Wake-density belt with three authored checkpoint asteroids, broad bubbles, and a flatter route profile.',
    },
    lore: {
      fieldNote: 'A marked warm-up lane cut through the same wake field. The rocks are spaced wide, and the route asks for calm exits before speed.',
      launchCallout: 'Wake Primer is live. Take the bubbles clean and keep the ship settled.',
      resultNote: 'Primer receipt stamped. The lane is simple, but a clean line still carries speed.',
      codexEntry: 'Wake Primer is the board crew easing pilots into asteroid-first racing. It uses the same crowded belt as Needle Wake, but the marked rocks are wider, softer, and easier to read from the cockpit.',
    },
    field: {
      gateClearance: 400,
      routeCorridor: 620,
      gravityAnchorCount: 3,
      hazardBias: 'medium',
      asteroidTuning: {
        PROCEDURAL_COUNT: 640,
        SPHERE_INNER: 680,
        SPHERE_OUTER: 12000,
        RADIUS_RANGE: 205,
        RADIAL_BIAS: 0.8,
        MASS_COEF: 9.2,
        CORE_DENSITY_MIN: 0.6,
        CORE_DENSITY_RANGE: 1.22,
        DRIFT_MIN: 0.02,
        DRIFT_RANGE: 0.08,
      },
      gravityAnchors: [
        { id: 'primer-first-wake', position: [420, 220, -1320], radius: 185, massScale: 0.56, visualIntensity: 0.8 },
        { id: 'primer-high-marker', position: [-360, 480, -2840], radius: 205, massScale: 0.62, visualIntensity: 0.84 },
        { id: 'primer-return-stone', position: [300, -160, -4600], radius: 195, massScale: 0.58, visualIntensity: 0.82 },
      ],
    },
    gates: [
      { id: 'primer-launch', label: 'Launch Ring', position: [0, 50, -560], radius: 165, beat: 'Launch into the first readable wake marker.' },
      { id: 'primer-first-wake', label: 'First Wake', anchor: { anchorId: 'primer-first-wake' }, radius: 520, beat: 'Enter the first asteroid bubble with a calm line.' },
      { id: 'primer-high-marker', label: 'High Marker', anchor: { anchorId: 'primer-high-marker' }, radius: 560, beat: 'Climb gently through the high marker.' },
      { id: 'primer-return-stone', label: 'Return Stone', anchor: { anchorId: 'primer-return-stone' }, radius: 540, beat: 'Let the last rock turn you toward the finish.' },
      { id: 'primer-finish', label: 'Finish Ring', position: [0, 0, -5800], radius: 250, beat: 'Finish the warm-up wake line.' },
    ],
  },
  {
    id: 'needle-wake',
    name: 'Needle Wake',
    summary: 'A vertical wake route with four readable asteroid checkpoints.',
    seed: 13570,
    startPosition: [0, 0, 260],
    medals: { gold: 82, silver: 110, bronze: 150 },
    design: {
      biome: 'dead-iron-belt',
      difficulty: 3,
      skillFocus: 'Vertical route reading, lift/drop transitions, and preserving speed through offset wells.',
      rhythm: ['launch ring', 'wake rise', 'needle crown', 'underhook', 'tail rock', 'finish ring'],
      generationPattern: 'Medium-density vertical belt route with four authored checkpoint asteroids and low drift hazards.',
    },
    lore: {
      fieldNote: 'Needle Wake climbs above the claim plane, then drops under it before the final finish line. The line is vertical first, lateral second.',
      launchCallout: 'Needle Wake is posted. Read the height before the distance.',
      resultNote: 'Needle Wake receipt stamped. Clean pilots spend less time fighting the drop.',
      codexEntry: 'Needle Wake was mapped around a stack of narrow survey returns. Racers turned the stack into a height test: rise early, drop deliberately, and carry the lower hook back upward.',
    },
    field: {
      gateClearance: 360,
      routeCorridor: 520,
      gravityAnchorCount: 4,
      hazardBias: 'medium',
      asteroidTuning: {
        PROCEDURAL_COUNT: 640,
        SPHERE_INNER: 680,
        SPHERE_OUTER: 13000,
        RADIUS_RANGE: 205,
        RADIAL_BIAS: 0.8,
        MASS_COEF: 9.6,
        CORE_DENSITY_MIN: 0.62,
        CORE_DENSITY_RANGE: 1.3,
        DRIFT_MIN: 0.02,
        DRIFT_RANGE: 0.08,
      },
      gravityAnchors: [
        { id: 'needle-wake-rise', position: [520, 520, -1500], radius: 190, massScale: 0.68, visualIntensity: 0.84 },
        { id: 'needle-crown', position: [-260, 980, -2920], radius: 220, massScale: 0.78, visualIntensity: 0.88 },
        { id: 'needle-underhook', position: [-420, -760, -5400], radius: 235, massScale: 0.86, visualIntensity: 0.92 },
        { id: 'needle-tail-rock', position: [360, -120, -7200], radius: 200, massScale: 0.68, visualIntensity: 0.84 },
      ],
    },
    gates: [
      { id: 'needle-launch', label: 'Launch Ring', position: [0, 60, -620], radius: 150, beat: 'Launch toward the rising wake.' },
      { id: 'needle-wake-rise', label: 'Wake Rise', anchor: { anchorId: 'needle-wake-rise' }, radius: 455, beat: 'Climb into the first rock and carry upward speed.' },
      { id: 'needle-crown', label: 'Needle Crown', anchor: { anchorId: 'needle-crown' }, radius: 520, beat: 'Top out without burning away the line.' },
      { id: 'needle-underhook', label: 'Underhook', anchor: { anchorId: 'needle-underhook' }, radius: 550, beat: 'Use the lower hook to bend back upward.' },
      { id: 'needle-tail-rock', label: 'Tail Rock', anchor: { anchorId: 'needle-tail-rock' }, radius: 470, beat: 'Clip the final rock cleanly.' },
      { id: 'needle-finish', label: 'Finish Ring', position: [0, 0, -8200], radius: 235, beat: 'Finish the wake run.' },
    ],
  },
  {
    id: 'blackglass-thread',
    name: 'Blackglass Thread',
    summary: 'A deep-field expert line through seven bright wells and a narrow return thread.',
    seed: 13720,
    startPosition: [0, 0, 340],
    medals: { gold: 176, silver: 232, bronze: 310 },
    design: {
      biome: 'black-core-field',
      difficulty: 4,
      skillFocus: 'High-speed commitment through strong wells, late route corrections, and deep-field landmark reading.',
      rhythm: ['launch ring', 'first shard', 'glass bend', 'dark catch', 'thread drop', 'far needle', 'return shard', 'exit well', 'finish ring'],
      generationPattern: 'Long black-core route with seven authored checkpoint asteroids, visual-only field density, and sparse real hazards.',
    },
    lore: {
      fieldNote: 'A blackglass line with enough distance to build dangerous speed. The marked wells are the thread; everything else is noise.',
      launchCallout: 'Blackglass Thread is live. Commit early and keep the next shard in view.',
      resultNote: 'Blackglass receipt stamped. Strong runs look reckless until the last two wells line up.',
      codexEntry: 'Blackglass Thread runs along a deep survey scar where dense rocks throw sharp returns against the timing hardware. It is not the longest route on the board, but it asks for the most trust in the next pull.',
    },
    field: {
      gateClearance: 500,
      routeCorridor: 760,
      gravityAnchorCount: 7,
      hazardBias: 'medium',
      asteroidTuning: {
        PROCEDURAL_COUNT: 780,
        VISUAL_COUNT: 5600,
        SPHERE_INNER: 760,
        SPHERE_OUTER: 26000,
        RADIUS_MIN: 9,
        RADIUS_RANGE: 250,
        RADIUS_POWER: 1.45,
        VISUAL_RADIUS_MIN: 12,
        VISUAL_RADIUS_RANGE: 190,
        VISUAL_RADIUS_POWER: 1.74,
        RADIAL_BIAS: 0.74,
        SIZE_INNER_MAX: 0.3,
        MASS_COEF: 9.8,
        CORE_DENSITY_MIN: 0.62,
        CORE_DENSITY_RANGE: 1.42,
        DRIFT_MIN: 0.02,
        DRIFT_RANGE: 0.08,
      },
      gravityAnchors: [
        { id: 'thread-first-shard', position: [920, -180, -2300], radius: 245, massScale: 0.82, visualIntensity: 0.88 },
        { id: 'thread-glass-bend', position: [-1620, 420, -5200], radius: 285, massScale: 0.94, visualIntensity: 0.92 },
        { id: 'thread-dark-catch', position: [2160, -520, -8350], radius: 330, massScale: 1.08, visualIntensity: 0.98 },
        { id: 'thread-drop', position: [760, -1040, -11300], radius: 300, massScale: 1.0, visualIntensity: 0.94 },
        { id: 'thread-far-needle', position: [-2480, -160, -14500], radius: 320, massScale: 1.06, visualIntensity: 0.96 },
        { id: 'thread-return-shard', position: [1560, 760, -17600], radius: 290, massScale: 0.92, visualIntensity: 0.9 },
        { id: 'thread-exit-well', position: [-460, 260, -20500], radius: 270, massScale: 0.84, visualIntensity: 0.88 },
      ],
    },
    gates: [
      { id: 'thread-launch', label: 'Launch Ring', position: [0, 80, -880], radius: 180, beat: 'Launch deep and choose the first shard early.' },
      { id: 'thread-first-shard', label: 'First Shard', anchor: { anchorId: 'thread-first-shard' }, radius: 585, beat: 'Build speed from the first marked well.' },
      { id: 'thread-glass-bend', label: 'Glass Bend', anchor: { anchorId: 'thread-glass-bend' }, radius: 675, beat: 'Let the bend carry the ship across the scar.' },
      { id: 'thread-dark-catch', label: 'Dark Catch', anchor: { anchorId: 'thread-dark-catch' }, radius: 780, beat: 'Catch the heavy well without braking too late.' },
      { id: 'thread-drop', label: 'Thread Drop', anchor: { anchorId: 'thread-drop' }, radius: 720, beat: 'Drop through the route thread and hold speed.' },
      { id: 'thread-far-needle', label: 'Far Needle', anchor: { anchorId: 'thread-far-needle' }, radius: 760, beat: 'Use the far marker to reverse the lateral line.' },
      { id: 'thread-return-shard', label: 'Return Shard', anchor: { anchorId: 'thread-return-shard' }, radius: 690, beat: 'Carry the return without climbing too much.' },
      { id: 'thread-exit-well', label: 'Exit Well', anchor: { anchorId: 'thread-exit-well' }, radius: 645, beat: 'Aim the final pull at the finish hardware.' },
      { id: 'thread-finish', label: 'Finish Ring', position: [0, 0, -23200], radius: 300, beat: 'Finish the blackglass thread.' },
    ],
  },
  {
    id: 'iron-switchback',
    name: 'Iron Switchback',
    summary: 'A technical belt course that folds across five asteroid checkpoints before a long exit burn.',
    seed: 13640,
    startPosition: [0, 0, 280],
    medals: { gold: 112, silver: 150, bronze: 205 },
    design: {
      biome: 'dead-iron-belt',
      difficulty: 3,
      skillFocus: 'Lateral reversals, braking before heavy wells, and keeping speed through alternating asteroid pulls.',
      rhythm: ['launch ring', 'red hook', 'left tooth', 'high cross', 'low return', 'exit hammer', 'finish ring'],
      generationPattern: 'Dense dead-iron switchback lane with five authored checkpoint asteroids and tighter route bubbles.',
    },
    lore: {
      fieldNote: 'Iron Switchback was cut through a folded claim seam where every marked rock throws the next turn across the nose.',
      launchCallout: 'Iron Switchback is live. Brake early for the hooks and keep the exit burn clean.',
      resultNote: 'Switchback receipt stamped. The course pays pilots who turn before the rock forces the issue.',
      codexEntry: 'Iron Switchback began as a miner shuttle shortcut and became a timing-board favorite once pilots realized the folded route made clean reversals visible from the first ring.',
    },
    field: {
      gateClearance: 330,
      routeCorridor: 500,
      gravityAnchorCount: 5,
      hazardBias: 'high',
      asteroidTuning: {
        PROCEDURAL_COUNT: 720,
        SPHERE_INNER: 620,
        SPHERE_OUTER: 15000,
        RADIUS_RANGE: 225,
        RADIAL_BIAS: 0.82,
        MASS_COEF: 10.4,
        CORE_DENSITY_MIN: 0.68,
        CORE_DENSITY_RANGE: 1.46,
        DRIFT_MIN: 0.025,
        DRIFT_RANGE: 0.11,
      },
      gravityAnchors: [
        { id: 'switchback-red-hook', position: [760, -260, -1650], radius: 210, massScale: 0.76, visualIntensity: 0.86 },
        { id: 'switchback-left-tooth', position: [-980, 160, -3420], radius: 230, massScale: 0.84, visualIntensity: 0.9 },
        { id: 'switchback-high-cross', position: [1240, 680, -5350], radius: 245, massScale: 0.9, visualIntensity: 0.92 },
        { id: 'switchback-low-return', position: [-1120, -520, -7350], radius: 235, massScale: 0.86, visualIntensity: 0.9 },
        { id: 'switchback-exit-hammer', position: [520, 80, -9300], radius: 250, massScale: 0.92, visualIntensity: 0.94 },
      ],
    },
    gates: [
      { id: 'switchback-launch', label: 'Launch Ring', position: [0, 40, -700], radius: 155, beat: 'Launch into the first right-side hook.' },
      { id: 'switchback-red-hook', label: 'Red Hook', anchor: { anchorId: 'switchback-red-hook' }, radius: 500, beat: 'Let the first hook bend the line left.' },
      { id: 'switchback-left-tooth', label: 'Left Tooth', anchor: { anchorId: 'switchback-left-tooth' }, radius: 545, beat: 'Catch the left tooth without over-rotating.' },
      { id: 'switchback-high-cross', label: 'High Cross', anchor: { anchorId: 'switchback-high-cross' }, radius: 580, beat: 'Climb across the lane and hold the reversal.' },
      { id: 'switchback-low-return', label: 'Low Return', anchor: { anchorId: 'switchback-low-return' }, radius: 560, beat: 'Drop under the return rock with the nose already moving right.' },
      { id: 'switchback-exit-hammer', label: 'Exit Hammer', anchor: { anchorId: 'switchback-exit-hammer' }, radius: 590, beat: 'Use the heavy exit pull to aim at the finish.' },
      { id: 'switchback-finish', label: 'Finish Ring', position: [0, 0, -10800], radius: 255, beat: 'Finish the switchback burn.' },
    ],
  },
  {
    id: 'core-spiral',
    name: 'Core Spiral',
    summary: 'An elite black-core spiral around eight heavy wells with a fast vertical unwind.',
    seed: 13880,
    startPosition: [0, 0, 360],
    medals: { gold: 214, silver: 284, bronze: 380 },
    design: {
      biome: 'black-core-field',
      difficulty: 5,
      skillFocus: 'Long-route memory, stacked vertical corrections, and surviving repeated high-mass gravity assists.',
      rhythm: ['launch ring', 'outer notch', 'upper hook', 'blind fall', 'core bite', 'lower crown', 'wide return', 'last flare', 'unwind well', 'finish ring'],
      generationPattern: 'Extended black-core spiral with eight authored checkpoint asteroids, strong landmark wells, and deep visual density.',
    },
    lore: {
      fieldNote: 'Core Spiral wraps a dead scanner pocket. The route is readable, but only if the next well is chosen before the current pull peaks.',
      launchCallout: 'Core Spiral is live. Commit to the spiral and unwind before the last flare eats the line.',
      resultNote: 'Core Spiral receipt stamped. The board crew will be checking that ghost twice.',
      codexEntry: 'Core Spiral was mapped after survey pilots found a chain of black-core returns turning around an empty pocket. Racing crews turned the chain into an endurance test for pilots who can remember height, distance, and pull strength at the same time.',
    },
    field: {
      gateClearance: 540,
      routeCorridor: 820,
      gravityAnchorCount: 8,
      hazardBias: 'high',
      asteroidTuning: {
        PROCEDURAL_COUNT: 860,
        VISUAL_COUNT: 6400,
        SPHERE_INNER: 820,
        SPHERE_OUTER: 30000,
        RADIUS_MIN: 10,
        RADIUS_RANGE: 280,
        RADIUS_POWER: 1.42,
        VISUAL_RADIUS_MIN: 12,
        VISUAL_RADIUS_RANGE: 210,
        VISUAL_RADIUS_POWER: 1.72,
        RADIAL_BIAS: 0.72,
        SIZE_INNER_MAX: 0.28,
        MASS_COEF: 10.8,
        CORE_DENSITY_MIN: 0.72,
        CORE_DENSITY_RANGE: 1.58,
        DRIFT_MIN: 0.02,
        DRIFT_RANGE: 0.09,
      },
      gravityAnchors: [
        { id: 'spiral-outer-notch', position: [1180, 320, -2600], radius: 270, massScale: 0.92, visualIntensity: 0.9 },
        { id: 'spiral-upper-hook', position: [-620, 1260, -5350], radius: 310, massScale: 1.02, visualIntensity: 0.94 },
        { id: 'spiral-blind-fall', position: [-1840, -260, -8350], radius: 335, massScale: 1.12, visualIntensity: 0.98 },
        { id: 'spiral-core-bite', position: [420, -1360, -11400], radius: 360, massScale: 1.22, visualIntensity: 1 },
        { id: 'spiral-lower-crown', position: [2280, -540, -14650], radius: 330, massScale: 1.08, visualIntensity: 0.96 },
        { id: 'spiral-wide-return', position: [-2140, 820, -18100], radius: 345, massScale: 1.14, visualIntensity: 0.98 },
        { id: 'spiral-last-flare', position: [1280, 1460, -21850], radius: 320, massScale: 1.04, visualIntensity: 0.96 },
        { id: 'spiral-unwind-well', position: [-360, -240, -25200], radius: 300, massScale: 0.94, visualIntensity: 0.92 },
      ],
    },
    gates: [
      { id: 'spiral-launch', label: 'Launch Ring', position: [0, 90, -940], radius: 190, beat: 'Launch toward the outer edge of the spiral.' },
      { id: 'spiral-outer-notch', label: 'Outer Notch', anchor: { anchorId: 'spiral-outer-notch' }, radius: 640, beat: 'Set the spiral angle from the first notch.' },
      { id: 'spiral-upper-hook', label: 'Upper Hook', anchor: { anchorId: 'spiral-upper-hook' }, radius: 735, beat: 'Climb into the upper hook and prepare the blind fall.' },
      { id: 'spiral-blind-fall', label: 'Blind Fall', anchor: { anchorId: 'spiral-blind-fall' }, radius: 795, beat: 'Drop through the blind side without losing the next marker.' },
      { id: 'spiral-core-bite', label: 'Core Bite', anchor: { anchorId: 'spiral-core-bite' }, radius: 855, beat: 'Survive the heaviest bite and turn early.' },
      { id: 'spiral-lower-crown', label: 'Lower Crown', anchor: { anchorId: 'spiral-lower-crown' }, radius: 785, beat: 'Ride the lower crown across the pocket.' },
      { id: 'spiral-wide-return', label: 'Wide Return', anchor: { anchorId: 'spiral-wide-return' }, radius: 820, beat: 'Take the wide return before the route snaps upward.' },
      { id: 'spiral-last-flare', label: 'Last Flare', anchor: { anchorId: 'spiral-last-flare' }, radius: 760, beat: 'Let the last flare lift the nose toward the unwind.' },
      { id: 'spiral-unwind-well', label: 'Unwind Well', anchor: { anchorId: 'spiral-unwind-well' }, radius: 715, beat: 'Unwind the spiral and line up the finish.' },
      { id: 'spiral-finish', label: 'Finish Ring', position: [0, 0, -27800], radius: 325, beat: 'Finish the core spiral.' },
    ],
  },
];
